AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - 'vendor/**/*'

Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/WordArray:
  Enabled: false

Metrics/AbcSize:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 40

Metrics/PerceivedComplexity:
  Max: 50

Metrics/MethodLength:
  Max: 75

Metrics/BlockLength:
  Max: 75

Style/IfUnlessModifier:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false
